# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/gdplisy9i5bl5d81disy3m2gbviq89x0-cmake-3.19.1/bin/cmake

# The command to remove a file.
RM = /nix/store/gdplisy9i5bl5d81disy3m2gbviq89x0-cmake-3.19.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/inuits/Projects/gmu-project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/inuits/Projects/gmu-project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/nix/store/gdplisy9i5bl5d81disy3m2gbviq89x0-cmake-3.19.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/nix/store/gdplisy9i5bl5d81disy3m2gbviq89x0-cmake-3.19.1/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/inuits/Projects/gmu-project/CMakeFiles /home/inuits/Projects/gmu-project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/inuits/Projects/gmu-project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gmu-nn

# Build rule for target.
gmu-nn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmu-nn
.PHONY : gmu-nn

# fast build rule for target.
gmu-nn/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmu-nn.dir/build.make CMakeFiles/gmu-nn.dir/build
.PHONY : gmu-nn/fast

cifar10.o: cifar10.cpp.o

.PHONY : cifar10.o

# target to build an object file
cifar10.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmu-nn.dir/build.make CMakeFiles/gmu-nn.dir/cifar10.cpp.o
.PHONY : cifar10.cpp.o

cifar10.i: cifar10.cpp.i

.PHONY : cifar10.i

# target to preprocess a source file
cifar10.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmu-nn.dir/build.make CMakeFiles/gmu-nn.dir/cifar10.cpp.i
.PHONY : cifar10.cpp.i

cifar10.s: cifar10.cpp.s

.PHONY : cifar10.s

# target to generate assembly for a file
cifar10.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmu-nn.dir/build.make CMakeFiles/gmu-nn.dir/cifar10.cpp.s
.PHONY : cifar10.cpp.s

convnn.o: convnn.cpp.o

.PHONY : convnn.o

# target to build an object file
convnn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmu-nn.dir/build.make CMakeFiles/gmu-nn.dir/convnn.cpp.o
.PHONY : convnn.cpp.o

convnn.i: convnn.cpp.i

.PHONY : convnn.i

# target to preprocess a source file
convnn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmu-nn.dir/build.make CMakeFiles/gmu-nn.dir/convnn.cpp.i
.PHONY : convnn.cpp.i

convnn.s: convnn.cpp.s

.PHONY : convnn.s

# target to generate assembly for a file
convnn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmu-nn.dir/build.make CMakeFiles/gmu-nn.dir/convnn.cpp.s
.PHONY : convnn.cpp.s

data.o: data.cpp.o

.PHONY : data.o

# target to build an object file
data.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmu-nn.dir/build.make CMakeFiles/gmu-nn.dir/data.cpp.o
.PHONY : data.cpp.o

data.i: data.cpp.i

.PHONY : data.i

# target to preprocess a source file
data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmu-nn.dir/build.make CMakeFiles/gmu-nn.dir/data.cpp.i
.PHONY : data.cpp.i

data.s: data.cpp.s

.PHONY : data.s

# target to generate assembly for a file
data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmu-nn.dir/build.make CMakeFiles/gmu-nn.dir/data.cpp.s
.PHONY : data.cpp.s

mnist.o: mnist.cpp.o

.PHONY : mnist.o

# target to build an object file
mnist.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmu-nn.dir/build.make CMakeFiles/gmu-nn.dir/mnist.cpp.o
.PHONY : mnist.cpp.o

mnist.i: mnist.cpp.i

.PHONY : mnist.i

# target to preprocess a source file
mnist.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmu-nn.dir/build.make CMakeFiles/gmu-nn.dir/mnist.cpp.i
.PHONY : mnist.cpp.i

mnist.s: mnist.cpp.s

.PHONY : mnist.s

# target to generate assembly for a file
mnist.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmu-nn.dir/build.make CMakeFiles/gmu-nn.dir/mnist.cpp.s
.PHONY : mnist.cpp.s

opencl.o: opencl.cpp.o

.PHONY : opencl.o

# target to build an object file
opencl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmu-nn.dir/build.make CMakeFiles/gmu-nn.dir/opencl.cpp.o
.PHONY : opencl.cpp.o

opencl.i: opencl.cpp.i

.PHONY : opencl.i

# target to preprocess a source file
opencl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmu-nn.dir/build.make CMakeFiles/gmu-nn.dir/opencl.cpp.i
.PHONY : opencl.cpp.i

opencl.s: opencl.cpp.s

.PHONY : opencl.s

# target to generate assembly for a file
opencl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmu-nn.dir/build.make CMakeFiles/gmu-nn.dir/opencl.cpp.s
.PHONY : opencl.cpp.s

thesis.o: thesis.cpp.o

.PHONY : thesis.o

# target to build an object file
thesis.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmu-nn.dir/build.make CMakeFiles/gmu-nn.dir/thesis.cpp.o
.PHONY : thesis.cpp.o

thesis.i: thesis.cpp.i

.PHONY : thesis.i

# target to preprocess a source file
thesis.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmu-nn.dir/build.make CMakeFiles/gmu-nn.dir/thesis.cpp.i
.PHONY : thesis.cpp.i

thesis.s: thesis.cpp.s

.PHONY : thesis.s

# target to generate assembly for a file
thesis.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gmu-nn.dir/build.make CMakeFiles/gmu-nn.dir/thesis.cpp.s
.PHONY : thesis.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gmu-nn"
	@echo "... cifar10.o"
	@echo "... cifar10.i"
	@echo "... cifar10.s"
	@echo "... convnn.o"
	@echo "... convnn.i"
	@echo "... convnn.s"
	@echo "... data.o"
	@echo "... data.i"
	@echo "... data.s"
	@echo "... mnist.o"
	@echo "... mnist.i"
	@echo "... mnist.s"
	@echo "... opencl.o"
	@echo "... opencl.i"
	@echo "... opencl.s"
	@echo "... thesis.o"
	@echo "... thesis.i"
	@echo "... thesis.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

